version: "3.7"
services:
  app:
    build:
      args:
        user: root
      context: ./
      dockerfile: Dockerfile
    image: sisconvenios-php
    container_name: sisconvenios-php
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - sisconvenios-data-imagenes:/var/www/public/imagenes
    networks:
      - sisconvenios-network
  nginx:
    image: nginx:alpine
    container_name: sisconvenios-nginx
    restart: unless-stopped
    ports:
      - 4001:8000
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sisconvenios-network
networks:
  sisconvenios-network:
    driver: bridge
volumes:
  sisconvenios-data-imagenes:

